/* GENERATED by scripts/counts.js — do not edit by hand.
   Counts are read from the content itself so displayed totals cannot drift. */
window.RC_COUNTS = {
  "experiments": 270,
  "scienceGames": 12,
  "weekendLists": 52,
  "generated": "2026-09-03"
};
(function(){
  function fill(){
    var c = window.RC_COUNTS;
    document.querySelectorAll('[data-count]').forEach(function(el){
      var v = c[el.getAttribute('data-count')];
      if (typeof v === 'number') el.textContent = v;
    });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', fill);
  else fill();
})();
