#!/usr/bin/env node
/* Regenerates js/counts.js from the content itself, so displayed totals can
   never drift from reality. Counts what can be counted; anything not derivable
   from a file stays in MANUAL below with a comment saying why.

   Run: node scripts/counts.js     (safe to run any time; writes js/counts.js) */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');

// experiments: count the array, not the header comment
const src = read('js/experiments-data.js');
const m = src.match(/const EXPERIMENTS\s*=\s*(\[[\s\S]*?\n\]);/);
if (!m) { console.error('counts: could not find the EXPERIMENTS array'); process.exit(1); }
const experiments = eval(m[1]).length;

// science games: every page in games/ except the hub
const scienceGames = fs.readdirSync(path.join(root, 'games'))
  .filter(f => f.endsWith('.html') && f !== 'index.html').length;

// weekend lists: the live page is hand-built, so this stays manual until the
// lists move into data/. Flagged rather than silently guessed.
const MANUAL = { weekendLists: 52 };

const out = { experiments, scienceGames, ...MANUAL, generated: new Date().toISOString().slice(0, 10) };

fs.writeFileSync(path.join(root, 'js/counts.js'),
`/* GENERATED by scripts/counts.js — do not edit by hand.
   Counts are read from the content itself so displayed totals cannot drift. */
window.RC_COUNTS = ${JSON.stringify(out, null, 2)};
(function(){
  function fill(){
    var c = window.RC_COUNTS;
    document.querySelectorAll('[data-count]').forEach(function(el){
      var v = c[el.getAttribute('data-count')];
      if (typeof v === 'number') el.textContent = v;
    });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', fill);
  else fill();
})();
`);
console.log('counts:', JSON.stringify(out));
